Nosto/nosto-magento

app/code/community/Nosto/Tagging/Helper/Price.php
app/code/community/Nosto/Tagging/Model/Base.php
app/code/community/Nosto/Tagging/Model/Meta/Order/Buyer.php
app/code/community/Nosto/Tagging/Model/Meta/Order/Item.php
app/code/community/Nosto/Tagging/Model/Meta/Order/Status.php
app/code/community/Nosto/Tagging/controllers/Adminhtml/NostoController.php
app/code/community/Nosto/Tagging/controllers/OauthController.php

- Module log file to a constant
- Remove error throwing for invalid data

Loosen up the validation

---

app/code/community/Nosto/Tagging/etc/config.xml
app/design/frontend/base/default/layout/nostotagging.xml

Add recommendation placeholders for 404 and thank-you pages, and, change save hook

---

app/code/community/Nosto/Tagging/Model/Resource/Product/Collection.php
app/code/community/Nosto/Tagging/controllers/ExportController.php

* Add possibility to filter exports with entity id
* Sort the collections by entity's creation time descending
Closes #54

Enhance export controllers to sort in a descending order and allow searching by id

---

app/code/community/Nosto/Tagging/Block/Checksum.php
app/code/community/Nosto/Tagging/Helper/Customer.php
app/code/community/Nosto/Tagging/Helper/Data.php
app/design/frontend/base/default/layout/nostotagging.xml
app/design/frontend/base/default/template/nostotagging/checksum.phtml

also switch cookie name to the helper class
Closes #56

Add visitor checksum for each page

---

CHANGELOG.md
app/code/community/Nosto/Tagging/Block/Searchterm.php
app/design/frontend/base/default/layout/nostotagging.xml
app/design/frontend/base/default/template/nostotagging/searchterm.phtml

Add search term tagging for search pages

---

app/code/community/Nosto/Tagging/Helper/Price.php
app/code/community/Nosto/Tagging/Model/Meta/Order.php

Deduct discount from ordered items

---

app/code/community/Nosto/Tagging/controllers/Adminhtml/NostoController.php

Add valid access control to Nosto controller

---

app/code/community/Nosto/Tagging/Helper/Price.php
app/code/community/Nosto/Tagging/Model/Meta/Order.php
app/code/community/Nosto/Tagging/controllers/ExportController.php

Add discount handling for ordered items

---

app/code/community/Nosto/Tagging/Model/Meta/Product.php
app/code/community/Nosto/Tagging/Model/Observer.php

After this we will also update "not visible" products into Nosto via API

Upsert invisible products and handle "Invisible" status

---

app/code/community/Nosto/Tagging/Model/Meta/Order.php
app/code/community/Nosto/Tagging/controllers/Adminhtml/NostoController.php

Fixes done in 2.6.10 but for 3.0.0

Hotfix/missing fixes from 2.6.x

---

app/code/community/Nosto/Tagging/etc/config.xml
app/code/community/Nosto/Tagging/sql/tagging_setup/mysql4-install-1.2.0.php
magazine.json

Add check if the table exists

---

app/code/community/Nosto/Tagging/Block/Cart.php
app/code/community/Nosto/Tagging/Block/Customer.php
app/code/community/Nosto/Tagging/Block/Order.php
app/code/community/Nosto/Tagging/Helper/Data.php
app/code/community/Nosto/Tagging/etc/config.xml
app/design/frontend/base/default/template/nostotagging/cart.phtml
app/design/frontend/base/default/template/nostotagging/customer.phtml
app/design/frontend/base/default/template/nostotagging/order.phtml

Add visitor checksum to customer, cart and order tagging

---

app/code/community/Nosto/Tagging/Helper/Account.php
app/code/community/Nosto/Tagging/Helper/Cache.php
app/code/community/Nosto/Tagging/Helper/Data.php

Improvements to the cache clearing when saving/removing accounts

---

app/code/community/Nosto/Tagging/Helper/Url.php
app/code/community/Nosto/Tagging/Model/System/Config/Source/Image.php
app/code/community/Nosto/Tagging/controllers/ExportController.php

* Remove useless addAttributeToSelect
* check image attribute object type in image selector souce model
* refactor url helper
Closes #154

Remove useless addAttributeToSelect & refactoring

---

app/code/community/Nosto/Tagging/Helper/Url.php
app/code/community/Nosto/Tagging/Model/Meta/Product.php
app/code/community/Nosto/Tagging/Model/Meta/Product/Url.php
app/code/community/Nosto/Tagging/controllers/ExportController.php

- fix product url key change
- fix the store parameter ignore for api calls (store context changes)

Fix product url key change

---

app/code/community/Nosto/Tagging/Helper/Price.php
app/code/community/Nosto/Tagging/Model/Meta/Product.php
app/design/frontend/base/default/template/nostotagging/product.phtml
build.xml
composer.json
composer.lock
magazine.json

* Remove date_published tagging
* bump sdk
* remove version from magazine
* change the price helper to use SDK's price helper

Remove date_published tagging

---

app/code/community/Nosto/Tagging/Block/Pagetype.php
app/design/frontend/base/default/layout/nostotagging.xml
app/design/frontend/base/default/template/nostotagging/pagetype.phtml

Added page type tagging to all the pages.

---

app/design/frontend/base/default/layout/nostotagging.xml
app/design/frontend/base/default/template/nostotagging/jsstub.phtml
magazine.json

Added the Nosto stub to before the Nosto direct include script

---

app/code/community/Nosto/Tagging/Block/Adminhtml/Iframe.php
app/code/community/Nosto/Tagging/Block/Adminhtml/Notifications.php
app/code/community/Nosto/Tagging/Helper/Customer.php
app/code/community/Nosto/Tagging/Helper/Data.php
app/code/community/Nosto/Tagging/Helper/Url.php
app/code/community/Nosto/Tagging/Model/Meta/Account.php
app/code/community/Nosto/Tagging/Model/Meta/Account/Iframe.php
app/code/community/Nosto/Tagging/Model/Meta/Oauth.php
app/code/community/Nosto/Tagging/Model/Observer.php

Fixes to the OAuth redirect URL when the use-store-code in URLs is enabled

---

app/code/community/Nosto/Tagging/Helper/Price.php

Use the lowest price from the child product for configurable products

---

app/code/community/Nosto/Tagging/Model/Meta/Product.php
composer.json
composer.lock

Add support for new product fields & bump PHP SDK version

---

app/code/community/Nosto/Tagging/controllers/OauthController.php

Add Oauth error as a parameter to the redirect URL

---

app/code/community/Nosto/Tagging/Block/Adminhtml/System/Config/Ratings/Provider.php
app/code/community/Nosto/Tagging/Helper/Class.php
app/code/community/Nosto/Tagging/Helper/Data.php
app/code/community/Nosto/Tagging/Helper/Rating.php
app/code/community/Nosto/Tagging/Helper/Stock.php
app/code/community/Nosto/Tagging/Model/Meta/Product.php
app/code/community/Nosto/Tagging/Model/Meta/Rating.php
app/code/community/Nosto/Tagging/Model/Meta/Rating/Interface.php
app/code/community/Nosto/Tagging/Model/Meta/Rating/Magento/Rating.php
app/code/community/Nosto/Tagging/Model/Meta/Rating/Yotpo/Yotpo.php
app/code/community/Nosto/Tagging/Model/System/Config/Source/Attribute.php
app/code/community/Nosto/Tagging/Model/System/Config/Source/Ratings/Provider.php
app/code/community/Nosto/Tagging/etc/config.xml
app/code/community/Nosto/Tagging/etc/system.xml
app/design/frontend/base/default/template/nostotagging/product.phtml

* support for Magento ratings & reviews
* support for Yotpo ratings
* add inventory level
Closes #215

Ratings & reviews support 

---

.gitignore
app/code/community/Nosto/Tagging/Helper/Class.php
app/code/community/Nosto/Tagging/Model/Meta/Order.php
app/code/community/Nosto/Tagging/Model/Meta/Product.php
app/code/community/Nosto/Tagging/Model/Meta/Product/Trait.php
app/code/community/Nosto/Tagging/Model/Meta/Sku.php
app/code/community/Nosto/Tagging/Model/Service/Product.php
app/code/community/Nosto/Tagging/bootstrap.php
app/design/frontend/base/default/template/nostotagging/product.phtml
build.xml
composer.lock
magazine.json

Initial support for working with product variations

---

app/code/community/Nosto/Tagging/Block/Stub.php
app/design/frontend/base/default/layout/nostotagging.xml

Support to conditionally render the stub if account exists

---

app/code/community/Nosto/Tagging/Block/Product.php
app/design/frontend/base/default/template/nostotagging/product.phtml

Added a flag to denote whether the product is overridden

---

app/design/frontend/base/default/template/nostotagging/product.phtml
composer.json

Add tagging for the thumbnail URL when specified

---

app/code/community/Nosto/Tagging/Model/Meta/Product.php
app/code/community/Nosto/Tagging/Model/Meta/Product/Tags/LowStock.php
composer.json

Add tagging to denote low-stock simple products

---

modman

Remove the PHPSeclib from the Modman file

---

app/code/community/Nosto/Tagging/Model/Meta/Product.php
app/code/community/Nosto/Tagging/Model/Meta/Product/Trait.php
app/code/community/Nosto/Tagging/Model/Meta/Sku.php

Update availability algorithm for SKUs

---

app/code/community/Nosto/Tagging/Helper/Data.php
app/code/community/Nosto/Tagging/Helper/Price.php
app/code/community/Nosto/Tagging/Model/Meta/Cart/Item.php
app/code/community/Nosto/Tagging/Model/Meta/Product/Trait.php

Add support for sending product and shopping cart item prices excluding tax

---

app/code/community/Nosto/Tagging/Helper/Event.php
app/code/community/Nosto/Tagging/Model/Meta/Cart.php
app/code/community/Nosto/Tagging/Model/Meta/Order.php
app/code/community/Nosto/Tagging/Model/Meta/Product.php

Add dispatching of nosto events

---

app/code/community/Nosto/Tagging/Block/Variation.php
app/code/community/Nosto/Tagging/Helper/Variation.php
app/code/community/Nosto/Tagging/Model/Meta/Account.php
app/code/community/Nosto/Tagging/Model/Meta/Product.php
app/code/community/Nosto/Tagging/Model/Meta/Settings.php
app/code/community/Nosto/Tagging/Model/Meta/Variation.php
app/code/community/Nosto/Tagging/Model/Meta/Variation/Collection.php
composer.json
composer.lock

* Add helper for resolving variation id (when using price variations)
* fix serialization
* add default variation id for the account

Price variation fixes

---

app/code/community/Nosto/Tagging/Model/Meta/Order/Buyer.php
composer.json
composer.lock

Add phone post code and country to person

---

app/code/community/Nosto/Tagging/Block/Addtocart.php
app/code/community/Nosto/Tagging/Block/Adminhtml/Notifications.php
app/code/community/Nosto/Tagging/Block/Cart.php
app/code/community/Nosto/Tagging/Block/Category.php
app/code/community/Nosto/Tagging/Block/Customer.php
app/code/community/Nosto/Tagging/Block/Element.php
app/code/community/Nosto/Tagging/Block/Embed.php
app/code/community/Nosto/Tagging/Block/Meta.php
app/code/community/Nosto/Tagging/Block/Order.php
app/code/community/Nosto/Tagging/Block/Pagetype.php
app/code/community/Nosto/Tagging/Block/Product.php
app/code/community/Nosto/Tagging/Block/Searchterm.php
app/code/community/Nosto/Tagging/Block/Stub.php
app/code/community/Nosto/Tagging/Block/Variation.php
app/code/community/Nosto/Tagging/Helper/Module.php
app/code/community/Nosto/Tagging/Model/Observer/Controller.php
app/code/community/Nosto/Tagging/Model/Observer/Order.php
app/code/community/Nosto/Tagging/Model/Observer/Product.php
app/code/community/Nosto/Tagging/bootstrap.php
app/code/community/Nosto/Tagging/controllers/Adminhtml/NostoController.php
app/code/community/Nosto/Tagging/controllers/CartController.php
app/code/community/Nosto/Tagging/controllers/ExportController.php

Check nosto dependencies before running

---

app/code/community/Nosto/Tagging/Block/Order.php
app/code/community/Nosto/Tagging/Block/Product.php
app/code/community/Nosto/Tagging/Helper/Url.php
app/code/community/Nosto/Tagging/Model/Meta/Account.php
app/code/community/Nosto/Tagging/Model/Meta/Product.php
app/code/community/Nosto/Tagging/Model/Meta/Product/Trait.php
app/code/community/Nosto/Tagging/controllers/ExportController.php

Fix ignore category issue

---

Jenkinsfile
app/code/community/Nosto/Tagging/Block/Adminhtml/Iframe.php
app/code/community/Nosto/Tagging/Helper/Rating.php
app/code/community/Nosto/Tagging/Helper/Url.php
app/code/community/Nosto/Tagging/Model/Service/Product.php
app/code/community/Nosto/Tagging/controllers/Adminhtml/NostoController.php
app/code/community/Nosto/Tagging/controllers/CartController.php
app/design/adminhtml/default/default/template/nostotagging/iframe.phtml
composer.json
composer.lock
phan.php

Add a button in nosto iframe page to go to configuration page

---

CHANGELOG.md
Dockerfile
Jenkinsfile
app/code/community/Nosto/Tagging/Helper/Price.php
app/code/community/Nosto/Tagging/etc/config.xml

Fix the list price for bundle product was aways same as final price issue
Closes #305

hotfix 3.3.4

---

app/code/community/Nosto/Tagging/Helper/Price.php

Check and apply catalog price rules to product's final price

---

app/code/community/Nosto/Tagging/Model/Meta/Cart/Item.php

Get converted price from cart item

---

CHANGELOG.md
app/code/community/Nosto/Tagging/Model/Service/Product.php
app/code/community/Nosto/Tagging/controllers/ExportController.php
app/code/community/Nosto/Tagging/etc/config.xml
app/design/frontend/base/default/template/nostotagging/product.phtml
build.xml
composer.json
composer.lock

Hotfix/3.3.7 - Add Nosto product validation

---

Jenkinsfile
composer.json
composer.lock

* Fix the OSL licence identifier to comply with SPDX License List
* Add composer validation to Jenkinsfile

Fix the OSL licence and add composer validation

---

app/code/community/Nosto/Tagging/Model/Observer/Product.php
app/code/community/Nosto/Tagging/Model/Service/Product.php
composer.json
composer.lock

Implement product deletion / discontinuing

---

CHANGELOG.md
app/code/community/Nosto/Tagging/Model/Meta/Cart/Item.php
app/code/community/Nosto/Tagging/etc/config.xml

Hotfix 3.5.3

---

app/code/community/Nosto/Tagging/etc/system.xml

Revisit send attributes from product text in Nosto settings

---

app/code/community/Nosto/Tagging/Helper/Data.php
app/code/community/Nosto/Tagging/Model/Observer/Setting.php
app/code/community/Nosto/Tagging/Model/System/Config/Source/Attribute.php
app/code/community/Nosto/Tagging/etc/config.xml

Invalidate indexer after Nosto settings have been modified

---

CHANGELOG.md
app/code/community/Nosto/Tagging/Helper/Price.php
app/code/community/Nosto/Tagging/etc/config.xml

hotfix 3.5.5

---

app/code/community/Nosto/Tagging/Model/Meta/Order/Builder.php
app/code/community/Nosto/Tagging/Model/Meta/Order/Item/Default.php
app/code/community/Nosto/Tagging/Model/Meta/Order/Item/Downloadable.php

Handle downloadable products in order

---

CHANGELOG.md
app/code/community/Nosto/Tagging/Helper/Price.php
app/code/community/Nosto/Tagging/etc/config.xml

- Fix the issue that the price of discounted bundle products could be tagged as 0 
Support ticket: NS-2145

Hotfix 3.6.3

---

CHANGELOG.md
app/code/community/Nosto/Tagging/Helper/Data.php
app/code/community/Nosto/Tagging/Helper/Url.php
app/code/community/Nosto/Tagging/Model/System/Config/Source/Restore/Cart/Location.php
app/code/community/Nosto/Tagging/controllers/CartController.php
app/code/community/Nosto/Tagging/etc/config.xml
app/code/community/Nosto/Tagging/etc/system.xml

Fix restore cart URL parameter handling

---

app/design/frontend/base/default/template/nostotagging/addtocart.phtml

Add Multiple Products To Cart Javascript Function

---

CHANGELOG.md
app/code/community/Nosto/Tagging/Block/Pagetype.php
app/code/community/Nosto/Tagging/etc/config.xml

Fixes an issue that prevent the PageType to be rendered on the Nosto debug toolbar
Closes #415

HotFix - 3.7.1

---

app/code/community/Nosto/Tagging/Model/Observer/Customer.php
app/code/community/Nosto/Tagging/Model/Service/Customer.php
app/code/community/Nosto/Tagging/etc/config.xml
composer.json
composer.lock

Update Marketing Permission Via Api Call

---

CHANGELOG.md
app/code/community/Nosto/Tagging/Block/Customer.php
app/code/community/Nosto/Tagging/Model/Meta/Cart.php
app/code/community/Nosto/Tagging/etc/config.xml

Fixes missing hcid from cart meta and customer block.

Hotfix 3.7.3 - Missing HCID Tagging

---

app/design/adminhtml/default/default/template/nostotagging/iframe.phtml

Feature - Add console log / console warning when iframe regexp test fails

---

app/code/community/Nosto/Tagging/Model/Meta/Product.php

Amend Attributes To Tags In Custom Fields

---

app/code/community/Nosto/Tagging/controllers/AddToCartController.php
app/design/frontend/base/default/template/nostotagging/addtocart.phtml

Feature - Add Support For Quantity In Add To Cart Javascript Function

---

CHANGELOG.md
app/code/community/Nosto/Tagging/etc/config.xml

Hotfix - 3.7.5

---

app/code/community/Nosto/Tagging/Model/Indexer/Product.php

Add expiry check to the Nosto index

---

CHANGELOG.md
app/code/community/Nosto/Tagging/Model/Meta/Product.php
app/code/community/Nosto/Tagging/Model/Meta/Product/Trait.php
app/code/community/Nosto/Tagging/Model/Meta/Sku.php
app/code/community/Nosto/Tagging/etc/config.xml

Add Store ID in Product and SKU Builder In Order To Set Attributes Values With The Correct Store Language

Hotfix 3.7.7 - Fix Attribute Names Translation

---

CHANGELOG.md
app/code/community/Nosto/Tagging/Helper/Data.php

- Add expiry check for Nosto indexed products. Related to #458

Bump Version and Update Changelog

---

app/code/community/Nosto/Tagging/shell/remove.php

Created command to remove connected nosto account

---

app/code/community/Nosto/Tagging/Model/Meta/Product.php

Correctly scoped the attribute to retrieve the proper value

---

CHANGELOG.md
app/code/community/Nosto/Tagging/Block/Adminhtml/System/Config/Inventory/Switch.php
app/code/community/Nosto/Tagging/Helper/Data.php
app/code/community/Nosto/Tagging/Model/Service/Order.php
app/code/community/Nosto/Tagging/etc/config.xml
app/code/community/Nosto/Tagging/etc/system.xml

Hotfix - Sync inventory level

---

composer.json
composer.lock

Bump Nosto SDK version to 3.9.0 to support HTTP 2
closes #475

Bump Nosto SDK version

---

CHANGELOG.md
Dockerfile
app/code/community/Nosto/Tagging/Block/Customer.php
app/code/community/Nosto/Tagging/etc/config.xml
composer.json
composer.lock

Fix double encoding in Oauth redirect URL and add null check for customer street address.
* Bump SDK
* Update change log
* Bump version 
* Add nullcheck for customer street address 
closes #479, #480 
* Undefined index error when street address doesn't contain "the second line"
* Fixes connecting Magento with existing Nosto account
* Tested manually customer tagging without the second address line
* Tested Oauth flow

Fix double encoding in Oauth redirectURL  & customer address fix

---

CHANGELOG.md
Dockerfile
app/code/community/Nosto/Tagging/Block/Customer.php
app/code/community/Nosto/Tagging/etc/config.xml
composer.json
composer.lock

Merge hotfix 3.8.3

---

CHANGELOG.md
app/code/community/Nosto/Tagging/Model/Meta/Product/Trait.php
app/code/community/Nosto/Tagging/etc/config.xml

Merge changes of hotfix/3.8.5 to develop branch

Merge hotfix 3.8.5

---

app/code/community/Nosto/Tagging/Helper/Data.php
app/code/community/Nosto/Tagging/etc/config.xml
app/code/community/Nosto/Tagging/etc/system.xml

Remove configuration about Real-Time Cart Updates. 
closes #496
Tested manually:
Removed configuration from core_config_data table.
Cleared cache. It returns false.

Remove Real-Time Cart Update configuration

---

app/code/community/Nosto/Tagging/Block/Searchterm.php
composer.json
composer.lock

Encode HTML characters that are present in product attribute values.
closes #495
Manually:
Created custom attributes and added HTML chars in their values

Encode all product attributes in tagging

---

app/code/community/Nosto/Tagging/Helper/Url.php
app/code/community/Nosto/Tagging/Model/Service/Order.php
app/code/community/Nosto/Tagging/Model/Service/Product.php
composer.lock

Add store domain and Nosto account in the headers of the API call. 
Cases added:
* Upsert Product
* Order Confirmation
closes #494
Tested manually, checked the headers are correct when making the call.

Add domain and nosto account in the API header

---

app/code/community/Nosto/Tagging/Model/Service/Recommendation/Category.php

Enable the preview mode in graphql, in order to get mock products. The preview will get automatically enabled when the user turn the preview switch in the debug toolbar.
closes #522

Set preview mode to true if cookie exists

---

CHANGELOG.md
app/code/community/Nosto/Tagging/Model/Meta/Sku.php
composer.json
composer.lock

Amend SKU entity to add product inventory level.
Closes #520 
We have the field available on Playcart, but we are not sending the data.
Built product, data has been checked on Playcart payload and UI.
Product has been correctly sanitized and there's no inventory level data on the tagging.
N/A

Feature - Add inventory level SKU

---

app/code/community/Nosto/Tagging/Block/Adminhtml/Iframe.php
app/code/community/Nosto/Tagging/Block/Adminhtml/System/Config/Currency/Method.php
app/code/community/Nosto/Tagging/Block/Cart.php
app/code/community/Nosto/Tagging/Block/Order.php
app/code/community/Nosto/Tagging/Helper/Account.php
app/code/community/Nosto/Tagging/Helper/Data.php
app/code/community/Nosto/Tagging/Helper/Oauth.php
app/code/community/Nosto/Tagging/Helper/Price.php
app/code/community/Nosto/Tagging/Helper/Rating.php
app/code/community/Nosto/Tagging/Model/Meta/Account.php
app/code/community/Nosto/Tagging/Model/Meta/Cart/Builder.php
app/code/community/Nosto/Tagging/Model/Meta/Cart/Item.php
app/code/community/Nosto/Tagging/Model/Meta/Order.php
app/code/community/Nosto/Tagging/Model/Meta/Order/Builder.php
app/code/community/Nosto/Tagging/Model/Meta/Order/Item.php
app/code/community/Nosto/Tagging/Model/Meta/Order/Vaimo/Klarna/Checkout.php
app/code/community/Nosto/Tagging/Model/Meta/Product.php
app/code/community/Nosto/Tagging/Model/Meta/Product/Builder.php
app/code/community/Nosto/Tagging/Model/Meta/Variation/Collection.php
app/code/community/Nosto/Tagging/Model/Observer/Cart.php
app/code/community/Nosto/Tagging/Model/Service/Product.php
app/code/community/Nosto/Tagging/Model/System/Config/Backend/Currency/Exchange/Rate/Cron.php
app/code/community/Nosto/Tagging/controllers/AddToCartController.php
app/code/community/Nosto/Tagging/controllers/Adminhtml/NostoController.php
app/code/community/Nosto/Tagging/controllers/OauthController.php

Suppress phan warnings, fix doc blocks & fix bugs where phan found one

Suppress phan warnings and fix doc blocks

---

.github/workflows/action.yml

Fixes the packaging to use magazine instead of composer archive

Fix the packaging to use magazine
